import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { IBM_Plex_Mono } from "next/font/google";

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const montserrat = Montserrat({subsets:['latin'],variable:'--font-sans'});

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xyraa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, jetbrainsMono.variable, "font-sans", montserrat.variable)}
    >
      <body className={plexMono.className}>
        <ThemeProvider
         attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
        >
          <Toaster/>
          <main className="w-full min-h-screen">
            <div className="">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
